### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by TheGrimSilence** [arcanis/clipanion#29]
I was wondering if you plan to add more documentation? I know Clipanion is... extensive, but more documentation would help. Lately I've just been tearing apart Yarn Modern's code to figure out how to use it better. Like throwing `UsageError` or extending it to make something like `WorkspaceRequiredError`. But these smaller things aren't mentioned in the README and there isn't a wiki.

**Comment by arcanis** [comment]
The problem with missing documentation is that since we know how to do it, we miss how hard it is to know about some features, so we don't know it needs documentation 😅

I think the best would be to submit a PR when you learn about something that should be documented, and little by little we'll get there! And in the meantime, feel free to ask in #contributing on the Yarn discord, perhaps we'll be able to point you to the right direction.

**Comment by TheGrimSilence** [comment]
I feel that I'm the same way 😂. Since I'm also using Clipanion to it's fullest I'll submit occasional PRs when I feel new devs could learn something new. I already wrote an article on Medium, [Getting started with Clipanion, the CLI library that powers Yarn Modern](https://medium.com/p/getting-started-with-clipanion-the-cli-library-that-powers-yarn-modern-92ba89f9c745?source=email-cde05bbeac19--writer.postDistributed&sk=ca90a33d52a711c757119ad8ee62ab83). Thanks for the response, cheers! 🍻

**Comment by merceyz** [comment]
Clipanion has a documentation website now https://mael.dev/clipanion :tada:

**Comment by arcanis** [comment]
Indeed! Closing this issue 👍
